--
-- PostgreSQL database dump
--






SET statement_timeout = 0;
SET lock_timeout = 0;


SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

;

-- cartads_dossier
CREATE TABLE cartads.cartads_dossier (
    cartads_dossier_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    commune text,
    n_commune integer,
    adresse text,
    liste_parcelles text,
    type_dossier text,
    annee integer,
    date_depot date,
    date_limite_instruction date,
    date_modification_dossier date,
    date_avis_instructeur date,
    date_decision date,
    date_notification_decision date,
    stade text,
    autorite text,
    instructeur text,
    avis_instructeur text,
    signataire text,
    decision text,
    demandeur_principal text,
    url_dossier text
);


-- cartads_dossier
COMMENT ON TABLE cartads.cartads_dossier IS 'Liste des parcelles historiques issue du cadastre.';


-- cartads_dossier_cartads_dossier_id_seq
ALTER TABLE cartads.cartads_dossier ALTER COLUMN cartads_dossier_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_cartads_dossier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- cartads_dossier_geo
CREATE TABLE cartads.cartads_dossier_geo (
    cartads_dossier_geo_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    geom geometry(MultiPolygon,2154),
    complete_geom boolean
);


-- cartads_dossier_geo
COMMENT ON TABLE cartads.cartads_dossier_geo IS 'Liste des dossiers Cart@DS avec une géométrie reconstruite à partir des parcelles';


-- cartads_dossier_geo_cartads_dossier_geo_id_seq
ALTER TABLE cartads.cartads_dossier_geo ALTER COLUMN cartads_dossier_geo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_geo_cartads_dossier_geo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- cartads_dossier_parcelle
CREATE TABLE cartads.cartads_dossier_parcelle (
    cartads_dossier_parcelle_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    cartads_parcelle text,
    geo_parcelle text
);


-- cartads_dossier_parcelle
COMMENT ON TABLE cartads.cartads_dossier_parcelle IS 'Liste des parcelles par dossiers Cart@DS.';


-- cartads_dossier_parcelle_cartads_dossier_parcelle_id_seq
ALTER TABLE cartads.cartads_dossier_parcelle ALTER COLUMN cartads_dossier_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_parcelle_cartads_dossier_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- cartads_dossier_parcelle_historique
CREATE TABLE cartads.cartads_dossier_parcelle_historique (
    cartads_dossier_parcelle_historique_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    cartads_parcelle_historique text,
    geo_parcelle_historique text,
    cartads_parcelle text,
    geo_parcelle text
);


-- cartads_dossier_parcelle_historique
COMMENT ON TABLE cartads.cartads_dossier_parcelle_historique IS 'Liste des parcelles historiques associées aux dossiers Cart@DS avec leur parcelle actuelle.';


-- cartads_dossier_parcelle_hist_cartads_dossier_parcelle_hist_seq
ALTER TABLE cartads.cartads_dossier_parcelle_historique ALTER COLUMN cartads_dossier_parcelle_historique_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_parcelle_hist_cartads_dossier_parcelle_hist_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- cartads_parcelle
CREATE TABLE cartads.cartads_parcelle (
    cartads_parcelle_id integer NOT NULL,
    geo_parcelle text,
    cartads_parcelle text,
    cartads_parcelle_url text,
    geom geometry(MultiPolygon,2154)
);


-- cartads_parcelle
COMMENT ON TABLE cartads.cartads_parcelle IS 'Liste des parcelles avec leur url vers l''API Cart@DS issue du cadastre.';


-- cartads_parcelle_cartads_parcelle_id_seq
ALTER TABLE cartads.cartads_parcelle ALTER COLUMN cartads_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_parcelle_cartads_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- cartads_parcelle_historique
CREATE TABLE cartads.cartads_parcelle_historique (
    cartads_parcelle_id integer NOT NULL,
    geo_parcelle text,
    cartads_parcelle text,
    date_debut date,
    date_fin date,
    geom geometry(MultiPolygon,2154)
);


-- cartads_parcelle_historique_cartads_parcelle_id_seq
ALTER TABLE cartads.cartads_parcelle_historique ALTER COLUMN cartads_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_parcelle_historique_cartads_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- communes
CREATE TABLE cartads.communes (
    communes_id integer NOT NULL,
    anneemajic integer,
    ccodep text,
    codcomm text,
    nom text,
    codeinsee character(5) NOT NULL,
    geom geometry(MultiPolygon,2154)
);


-- communes
COMMENT ON TABLE cartads.communes IS 'Table des communes issue du cadastre.';


-- communes_communes_id_seq
ALTER TABLE cartads.communes ALTER COLUMN communes_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.communes_communes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- geo_zones
CREATE TABLE cartads.geo_zones (
    geo_zones_id integer NOT NULL,
    zones_id integer NOT NULL,
    zones_nom text NOT NULL,
    codeinsee character(5) NOT NULL,
    geom geometry(Polygon,2154)
);


-- geo_zones
COMMENT ON TABLE cartads.geo_zones IS 'Zones urba avec les géométries.';


-- geo_zones_geo_zones_id_seq
ALTER TABLE cartads.geo_zones ALTER COLUMN geo_zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.geo_zones_geo_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- glossary_zones
CREATE TABLE cartads.glossary_zones (
    glossary_zones_id integer NOT NULL,
    zones_type text NOT NULL,
    zones_type_code character(1) NOT NULL
);


-- glossary_zones
COMMENT ON TABLE cartads.glossary_zones IS 'Glossaires des Zones urba Cart@DS.';


-- glossary_zones_glossary_zones_id_seq
ALTER TABLE cartads.glossary_zones ALTER COLUMN glossary_zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.glossary_zones_glossary_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


-- metadata
CREATE TABLE cartads.metadata (
    id integer NOT NULL,
    me_version text NOT NULL,
    me_version_date date NOT NULL,
    me_status smallint NOT NULL
);


-- metadata
COMMENT ON TABLE cartads.metadata IS 'Metadata of the structure : version and date. Useful for database structure and glossary data migrations between versions';


-- new_cartads_dossier
CREATE TABLE cartads.new_cartads_dossier (
    id_dossier integer,
    nom_dossier text,
    commune text,
    n_commune integer,
    adresse text,
    liste_parcelles text,
    type_dossier text,
    annee integer,
    date_depot date,
    date_limite_instruction date,
    date_modification_dossier date,
    date_avis_instructeur date,
    date_decision date,
    date_notification_decision date,
    stade text,
    autorite text,
    instructeur text,
    avis_instructeur text,
    signataire text,
    decision text,
    demandeur_principal text,
    url_dossier text
);


-- zones
CREATE TABLE cartads.zones (
    zones_id integer NOT NULL,
    zones_type text NOT NULL,
    zones_type_code character(1) NOT NULL,
    zones_nom text NOT NULL,
    zones_observation text,
    CONSTRAINT check_zones_type CHECK ((zones_type = ANY (ARRAY['Zonage'::text, 'Contrainte annexe'::text, 'Servitude d''utilité publique'::text, 'Prescription d''urbanisme'::text, 'Document annexe'::text]))),
    CONSTRAINT check_zones_type_code CHECK ((zones_type_code = ANY (ARRAY['Z'::character(1), 'C'::character(1), 'S'::character(1), 'P'::character(1), 'D'::character(1)])))
);


-- zones
COMMENT ON TABLE cartads.zones IS 'Liste des différentes zones d''urbanismes.
Le champ "zones_type" =  ''Zonage'', ''Contrainte annexe'', ''Servitude d''''utilité publique'', ''Prescription d''''urbanisme'', ''Document annexe''.
Le champ "zones_type_code " = ''Z'', ''C'', ''S'', ''P'', ''D''.
 ';


-- zones_zones_id_seq
ALTER TABLE cartads.zones ALTER COLUMN zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.zones_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- PostgreSQL database dump complete
--



