DROP TABLE IF EXISTS cartads.glossary_test_category CASCADE;
DROP TABLE IF EXISTS cartads.test CASCADE;


--
-- Name: cartads; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA cartads;


--
-- Name: SCHEMA cartads; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA cartads IS 'Schéma Administration des Droits du Sol pour la mise en place du connecteur cart@ds';


--
-- Name: polygons_intersection(text, text, text, text, text, text, text, text, text, integer); Type: FUNCTION; Schema: cartads; Owner: -
--

CREATE FUNCTION cartads.polygons_intersection(_schema_a text, _table_a text, _pk_field_a text, _geom_field_a text, _schema_b text, _table_b text, _pk_field_b text, _geom_field_b text, _condition text DEFAULT NULL::text, _limit integer DEFAULT NULL::integer) RETURNS TABLE(pk_a integer, pk_b integer, geom public.geometry)
    LANGUAGE plpgsql
    AS $_$
BEGIN
  RETURN QUERY EXECUTE
  format(
  $$
    SELECT (%3$s)::int AS pk_a, (%7$s)::int AS pk_b,
    ST_Multi(st_collectionextract(ST_Intersection(a."%4$s", b."%8$s"), 3)) AS geom
    FROM "%1$s"."%2$s" a
    JOIN "%5$s"."%6$s" b ON ST_INTERSECTS(a."%4$s", b."%8$s")
    %9$s
    GROUP BY pk_a, pk_b
    ORDER BY pk_a, pk_b
    %10$s
  $$,
  _schema_a,
  _table_a,
  _pk_field_a,
  _geom_field_a,
  _schema_b,
  _table_b,
  _pk_field_b,
  _geom_field_b,
  ('WHERE ' || _condition),
  ('LIMIT ' || _limit)
  );
END
$_$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cartads_dossier; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_dossier (
    cartads_dossier_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    commune text,
    n_commune integer,
    adresse text,
    liste_parcelles text,
    type_dossier text,
    annee integer,
    date_depot date,
    date_limite_instruction date,
    date_modification_dossier date,
    date_avis_instructeur date,
    date_decision date,
    date_notification_decision date,
    stade text,
    autorite text,
    instructeur text,
    avis_instructeur text,
    signataire text,
    decision text,
    demandeur_principal text,
    url_dossier text
);


--
-- Name: TABLE cartads_dossier; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_dossier IS 'Liste des dossiers disponibles au travers de Cart@DS.';


--
-- Name: cartads_dossier_cartads_dossier_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_dossier ALTER COLUMN cartads_dossier_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_cartads_dossier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_dossier_geo; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_dossier_geo (
    cartads_dossier_geo_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    geom public.geometry(MultiPolygon,2154),
    complete_geom boolean
);


--
-- Name: TABLE cartads_dossier; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_dossier_geo IS 'Liste des dossiers Cart@DS avec une géométrie reconstruite à partir des parcelles';


--
-- Name: cartads_dossier_geo_cartads_dossier_geo_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_dossier_geo ALTER COLUMN cartads_dossier_geo_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_geo_cartads_dossier_geo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_dossier_parcelle; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_dossier_parcelle (
    cartads_dossier_parcelle_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    cartads_parcelle text,
    geo_parcelle text
);


--
-- Name: TABLE cartads_dossier; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_dossier_parcelle IS 'Liste des parcelles par dossiers Cart@DS.';


--
-- Name: cartads_dossier_parcelle_cartads_dossier_parcelle_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_dossier_parcelle ALTER COLUMN cartads_dossier_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_parcelle_cartads_dossier_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_dossier_parcelle_historique; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_dossier_parcelle_historique (
    cartads_dossier_parcelle_historique_id integer NOT NULL,
    id_dossier integer,
    nom_dossier text,
    cartads_parcelle_historique text,
    geo_parcelle_historique text,
    cartads_parcelle text,
    geo_parcelle text
);


--
-- Name: TABLE cartads_dossier; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_dossier_parcelle_historique IS 'Liste des parcelles historiques associées aux dossiers Cart@DS avec leur parcelle actuelle.';


--
-- Name: cartads_dossier_parcelle_hist_cartads_dossier_parcelle_hist_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_dossier_parcelle_historique ALTER COLUMN cartads_dossier_parcelle_historique_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_dossier_parcelle_hist_cartads_dossier_parcelle_hist_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_parcelle; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_parcelle (
    cartads_parcelle_id integer NOT NULL,
    geo_parcelle text,
    cartads_parcelle text,
    cartads_parcelle_url text,
    geom public.geometry(MultiPolygon,2154)
);


--
-- Name: TABLE cartads_parcelle; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_parcelle IS 'Liste des parcelles avec leur url vers l''API Cart@DS issue du cadastre.';


--
-- Name: cartads_parcelle_cartads_parcelle_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_parcelle ALTER COLUMN cartads_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_parcelle_cartads_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_parcelle_historique; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.cartads_parcelle_historique (
    cartads_parcelle_id integer NOT NULL,
    geo_parcelle text,
    cartads_parcelle text,
    date_debut date,
    date_fin date,
    geom public.geometry(MultiPolygon,2154)
);


--
-- Name: TABLE cartads_dossier; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.cartads_dossier IS 'Liste des parcelles historiques issue du cadastre.';


--
-- Name: cartads_parcelle_historique_cartads_parcelle_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.cartads_parcelle_historique ALTER COLUMN cartads_parcelle_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.cartads_parcelle_historique_cartads_parcelle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: communes; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.communes (
    communes_id integer NOT NULL,
    anneemajic integer,
    ccodep text,
    codcomm text,
    nom text,
    codeinsee character(5) NOT NULL,
    geom public.geometry(MultiPolygon,2154)
);


--
-- Name: TABLE communes; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.communes IS 'Table des communes issue du cadastre.';


--
-- Name: communes_communes_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.communes ALTER COLUMN communes_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.communes_communes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: geo_zones; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.geo_zones (
    geo_zones_id integer NOT NULL,
    zones_id integer NOT NULL,
    zones_nom text NOT NULL,
    codeinsee character(5) NOT NULL,
    geom public.geometry(Polygon,2154)
);


--
-- Name: TABLE geo_zones; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.geo_zones IS 'Zones urba avec les géométries.';


--
-- Name: geo_zones_geo_zones_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.geo_zones ALTER COLUMN geo_zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.geo_zones_geo_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: glossary_zones; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.glossary_zones (
    glossary_zones_id integer NOT NULL,
    zones_type text NOT NULL,
    zones_type_code character(1) NOT NULL
);


--
-- Name: TABLE glossary_zones; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.glossary_zones IS 'Glossaires des Zones urba Cart@DS.';


--
-- Name: geo_zones_geo_zones_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.glossary_zones ALTER COLUMN glossary_zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.glossary_zones_glossary_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: new_cartads_dossier; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.new_cartads_dossier (
    id_dossier integer,
    nom_dossier text,
    commune text,
    n_commune integer,
    adresse text,
    liste_parcelles text,
    type_dossier text,
    annee integer,
    date_depot date,
    date_limite_instruction date,
    date_modification_dossier date,
    date_avis_instructeur date,
    date_decision date,
    date_notification_decision date,
    stade text,
    autorite text,
    instructeur text,
    avis_instructeur text,
    signataire text,
    decision text,
    demandeur_principal text,
    url_dossier text
);


--
-- Name: zones; Type: TABLE; Schema: cartads; Owner: -
--

CREATE TABLE cartads.zones (
    zones_id integer NOT NULL,
    zones_type text NOT NULL,
    zones_type_code character(1) NOT NULL,
    zones_nom text NOT NULL,
    zones_observation text,
    CONSTRAINT check_zones_type CHECK ((zones_type = ANY (ARRAY['Zonage'::text, 'Contrainte annexe'::text, 'Servitude d''utilité publique'::text, 'Prescription d''urbanisme'::text, 'Document annexe'::text]))),
    CONSTRAINT check_zones_type_code CHECK ((zones_type_code = ANY (ARRAY['Z'::character(1), 'C'::character(1), 'S'::character(1), 'P'::character(1), 'D'::character(1)])))
);


--
-- Name: TABLE zones; Type: COMMENT; Schema: cartads; Owner: -
--

COMMENT ON TABLE cartads.zones IS 'Liste des différentes zones d''urbanismes.
Le champ "zones_type" =  ''Zonage'', ''Contrainte annexe'', ''Servitude d''''utilité publique'', ''Prescription d''''urbanisme'', ''Document annexe''.
Le champ "zones_type_code " = ''Z'', ''C'', ''S'', ''P'', ''D''.
 ';


--
-- Name: zones_zones_id_seq; Type: SEQUENCE; Schema: cartads; Owner: -
--

ALTER TABLE cartads.zones ALTER COLUMN zones_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME cartads.zones_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cartads_dossier_geo cartads_dossier_geo_id_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_geo
    ADD CONSTRAINT cartads_dossier_geo_id_dossier_key UNIQUE (id_dossier);


--
-- Name: cartads_dossier_geo cartads_dossier_geo_nom_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_geo
    ADD CONSTRAINT cartads_dossier_geo_nom_dossier_key UNIQUE (nom_dossier);


--
-- Name: cartads_dossier_geo cartads_dossier_geo_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_geo
    ADD CONSTRAINT cartads_dossier_geo_pkey PRIMARY KEY (cartads_dossier_geo_id);


--
-- Name: cartads_dossier cartads_dossier_id_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier
    ADD CONSTRAINT cartads_dossier_id_dossier_key UNIQUE (id_dossier);


--
-- Name: cartads_dossier cartads_dossier_nom_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier
    ADD CONSTRAINT cartads_dossier_nom_dossier_key UNIQUE (nom_dossier);


--
-- Name: cartads_dossier_parcelle_historique cartads_dossier_parcelle_historique_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_parcelle_historique
    ADD CONSTRAINT cartads_dossier_parcelle_historique_pkey PRIMARY KEY (cartads_dossier_parcelle_historique_id);


--
-- Name: cartads_dossier_parcelle cartads_dossier_parcelle_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_parcelle
    ADD CONSTRAINT cartads_dossier_parcelle_pkey PRIMARY KEY (cartads_dossier_parcelle_id);


--
-- Name: cartads_dossier cartads_dossier_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier
    ADD CONSTRAINT cartads_dossier_pkey PRIMARY KEY (cartads_dossier_id);


--
-- Name: cartads_parcelle cartads_parcelle_cartads_parcelle_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle
    ADD CONSTRAINT cartads_parcelle_cartads_parcelle_key UNIQUE (cartads_parcelle);


--
-- Name: cartads_parcelle cartads_parcelle_geo_parcelle_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle
    ADD CONSTRAINT cartads_parcelle_geo_parcelle_key UNIQUE (geo_parcelle);


--
-- Name: cartads_parcelle_historique cartads_parcelle_historique_cartads_parcelle_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle_historique
    ADD CONSTRAINT cartads_parcelle_historique_cartads_parcelle_key UNIQUE (cartads_parcelle);


--
-- Name: cartads_parcelle_historique cartads_parcelle_historique_geo_parcelle_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle_historique
    ADD CONSTRAINT cartads_parcelle_historique_geo_parcelle_key UNIQUE (geo_parcelle);


--
-- Name: cartads_parcelle_historique cartads_parcelle_historique_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle_historique
    ADD CONSTRAINT cartads_parcelle_historique_pkey PRIMARY KEY (cartads_parcelle_id);


--
-- Name: cartads_parcelle cartads_parcelle_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_parcelle
    ADD CONSTRAINT cartads_parcelle_pkey PRIMARY KEY (cartads_parcelle_id);


--
-- Name: communes communes_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.communes
    ADD CONSTRAINT communes_pkey PRIMARY KEY (communes_id);


--
-- Name: geo_zones geo_zones_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.geo_zones
    ADD CONSTRAINT geo_zones_pkey PRIMARY KEY (geo_zones_id);


--
-- Name: glossary_zones glossary_zones_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.glossary_zones
    ADD CONSTRAINT glossary_zones_pkey PRIMARY KEY (glossary_zones_id);


--
-- Name: cartads_dossier_parcelle id_dossier_cartads_parcelle_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.cartads_dossier_parcelle
    ADD CONSTRAINT id_dossier_cartads_parcelle_key UNIQUE (id_dossier, cartads_parcelle);


--
-- Name: new_cartads_dossier new_cartads_dossier_id_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.new_cartads_dossier
    ADD CONSTRAINT new_cartads_dossier_id_dossier_key UNIQUE (id_dossier);


--
-- Name: new_cartads_dossier new_cartads_dossier_nom_dossier_key; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.new_cartads_dossier
    ADD CONSTRAINT new_cartads_dossier_nom_dossier_key UNIQUE (nom_dossier);


--
-- Name: zones zones_pkey; Type: CONSTRAINT; Schema: cartads; Owner: -
--

ALTER TABLE ONLY cartads.zones
    ADD CONSTRAINT zones_pkey PRIMARY KEY (zones_id);


--
-- Name: cartads_parcelle_geom_idx; Type: INDEX; Schema: cartads; Owner: -
--

CREATE INDEX cartads_parcelle_geom_idx ON cartads.cartads_parcelle USING gist (geom);


--
-- Name: cartads_parcelle_historique_geom_idx; Type: INDEX; Schema: cartads; Owner: -
--

CREATE INDEX cartads_parcelle_historique_geom_idx ON cartads.cartads_parcelle_historique USING gist (geom);


--
-- Data for Name: glossary_zones; Type: TABLE DATA; Schema: cartads; Owner: -
--

INSERT INTO cartads.glossary_zones (zones_type, zones_type_code) VALUES ('Zonage', 'Z');
INSERT INTO cartads.glossary_zones (zones_type, zones_type_code) VALUES ('Contrainte annexe', 'C');
INSERT INTO cartads.glossary_zones (zones_type, zones_type_code) VALUES ('Servitude d''utilité publique', 'C');
INSERT INTO cartads.glossary_zones (zones_type, zones_type_code) VALUES ('Prescription d''urbanisme', 'P');
INSERT INTO cartads.glossary_zones (zones_type, zones_type_code) VALUES ('Document annexe', 'D');
